const AMENITIES = {
  WIFI: "wi-fi",
  FIREPLACE: "fireplace",
  HEATING: "heating",
  AIR_CONDITIONING: "air conditioning",
  PRIVATE_POOL: "private pool",
  HOT_TUB_JACUZZI: "hot tub / jacuzzi",
  GARDEN_GROUNDS: "garden / grounds",
  TERRACE_BALCONY: "terrace / balcony",
  PARKING: "parking",
  BREAKFAST_INCLUDED: "breakfast included",
  PET_FRIENDLY: "pet friendly",
  WHEELCHAIR_ACCESSIBLE: "wheelchair accessible",
  SECURITY_SYSTEM: "security system",
  CONCIERGE_24_7: "24/7 concierge",
  INDOOR_FIREPLACE: "indoor fireplace",
  OUTDOOR_FIREPLACE: "outdoor fireplace",
  HISTORIC_ARCHITECTURE: "historic architecture",
  CASTLE_TOUR_AVAILABLE: "castle tour available",
  EVENT_HOSTING: "event hosting",
  WEDDING_VENUE: "wedding venue",
  LIBRARY_READING_ROOM: "library / reading room",
  GAME_ROOM: "game room",
  HOME_THEATER: "home theater",
  FITNESS_CENTER_GYM: "fitness center / gym",
  SAUNA: "sauna",
  FIRE_PIT: "fire pit",
  HORSEBACK_RIDING_ACCESS: "horseback riding access",
  TENNIS_COURT: "tennis court",
  GOLF_COURSE_NEARBY: "golf course nearby",
  WINE_CELLAR: "wine cellar",
  CATERING_SERVICES: "catering services",
  BABYSITTING_SERVICES: "babysitting services",
  LAUNDRY_FACILITIES: "laundry facilities",
  ELECTRIC_VEHICLE_CHARGING_STATION: "electric vehicle charging station",
  FISHING_ACCESS: "fishing access",
  BOAT_DOCK_MARINA: "boat dock / marina",
  PRIVATE_CHEF_AVAILABLE: "private chef available",
  BREAKFAST_AREA: "breakfast area",
  BREAKFAST_NOOK: "breakfast nook",
  HORSE_STABLE: "horse stable",
  HISTORIC_LANDMARK: "historic landmark",
  CHAPEL_PRAYER_ROOM: "chapel / prayer room",
  GYM: "gym"
};

export default AMENITIES;